list: $/synoptica/profile/models/profile/columns.yaml
modelClass: Synoptica\Profile\Models\Profile
title: Profiles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'synoptica/profile/profiles/update/:id'
